# Pages
pages:
- Home: index.md
- Notebook:
  - Programing: 
    - Python: 'notesmd/programing/python.md'
    - Snakemake: 'notesmd/programing/snakemake.md'
    - Biopython: 'notesmd/programing/biopython.md'
- Project on Github: project.md
- Publish: publish.md
- About me: me.md


# Project information
site_name: Xuan's notebook
site_description: 'A Personal Noteboos'
site_author: 'Xuan Zhang'
site_url: 'https://xuanblo.github.io'

# Repository
repo_name: "xuanblo/notebook"
repo_url: "https://github.com/xuanblo/notebook"


# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Xuan Zhang'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Blue Grey'
    accent: 'Green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'



# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/xuanblo'
    - type: 'ResearchGate'
      link: 'https://www.researchgate.net/profile/Xuan_Zhang91'

# Google Analytics
google_analytics:
  - 'UA-117843700-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

